### PR TITLE
Upgrade sha3 to make it compile on node 10

### PR DESCRIPTION
**Pull request by roderik**

### CODE REVIEW

**Comment by fanatid** [comment]
Can you describe why this package do not work on node 10 with current dependencies?

**Comment by roderik** [comment]
node-sha3 does not compile unless you have at least 1.2.1: https://github.com/phusion/node-sha3/releases

**Comment by fanatid** [comment]
If problem only in `node-sha3`, why you updated `browserify-sha3`?

**Comment by roderik** [comment]
Since you already allow it in your versioning scheme, there is no reason not to. 
But if there is an explicit reason to support such an old version, just kick that one out.

**Comment by danihodovic** [comment]
Can we please merge this? I'm facing the same problems. Using sha3@v1.2.2 works with Node 10.

https://asciinema.org/a/AcIw0i6u0anYFnNIJNV1GX7Ik

```
/root/.node-gyp/10.5.0/include/node/v8.h:3914:44: note:   candidate expects 1 argument, 2 provided
sha3.target.mk:99: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: Leaving directory '/app/node_modules/keccakjs/node_modules/sha3/build'
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/keccakjs/node_modules/sha3
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

**Comment by davidmurdoch** [comment]
If you could move `sha3` over to `optionalDependencies` Windows users won't even need windows-build-tools (which doesn't always work correctly anyway) installed to get this package working.

**Comment by danihodovic** [comment]
@axic @fanatid is this repository unmaintained?

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
@roderik @davidmurdoch sorry for the delays.

**Comment by axic** [comment]
Published 0.2.3.

**Pull request merged**
